import "dotenv/config";
import express from "express"; import cors from "cors"; import bcrypt from "bcryptjs"; import jwt from "jsonwebtoken";
import {db} from "./db.js"; import {auth,admin,AuthRequest} from "./middleware/auth.js";
const app=express(); app.use(cors({origin:process.env.CORS_ORIGIN?.split(",")||true})); app.use(express.json());
const secret=process.env.JWT_SECRET||"dev-secret";
app.get("/health",(_,res)=>res.json({ok:true,version:"1.0.0"}));
app.post("/api/auth/register",async(req,res)=>{const{name,phone,password}=req.body;if(!name||!phone||!password)return res.status(400).json({message:"بيانات ناقصة"});try{const hash=await bcrypt.hash(password,12);const u=await db.user.create({data:{name,phone,password:hash}});const token=jwt.sign({id:u.id,role:u.role},secret,{expiresIn:"30d"});res.json({token,user:{id:u.id,name:u.name,phone:u.phone,role:u.role}});}catch{res.status(409).json({message:"رقم الهاتف مستخدم"});}});
app.post("/api/auth/login",async(req,res)=>{const{phone,password}=req.body;const u=await db.user.findUnique({where:{phone}});if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({message:"بيانات غير صحيحة"});const token=jwt.sign({id:u.id,role:u.role},secret,{expiresIn:"30d"});res.json({token,user:{id:u.id,name:u.name,phone:u.phone,role:u.role}});});
app.get("/api/categories",async(_,res)=>res.json(await db.category.findMany({where:{active:true},include:{products:{where:{active:true}}}})));
app.get("/api/products",async(req,res)=>{const categoryId=String(req.query.categoryId||"");res.json(await db.product.findMany({where:{active:true,...(categoryId?{categoryId}:{})}}));});
app.get("/api/ads/config",async(_,res)=>res.json(await db.adConfig.findMany({where:{enabled:true}})));
app.post("/api/orders",auth,async(req:AuthRequest,res)=>{const{items,address,phone}=req.body;if(!Array.isArray(items)||!items.length||!address||!phone)return res.status(400).json({message:"بيانات الطلب ناقصة"});const ids=items.map((x:any)=>x.productId);const products=await db.product.findMany({where:{id:{in:ids},active:true}});const map=new Map(products.map(p=>[p.id,p]));let total=0;const normalized=[];for(const x of items){const p=map.get(x.productId);const q=Math.max(1,Number(x.quantity||1));if(!p)return res.status(400).json({message:"منتج غير متاح"});total+=Number(p.price)*q;normalized.push({productId:p.id,quantity:q,unitPrice:p.price});}const order=await db.order.create({data:{userId:req.user!.id,address,phone,total,items:{create:normalized}},include:{items:{include:{product:true}}}});res.status(201).json(order);});
app.get("/api/orders/my",auth,async(req:AuthRequest,res)=>res.json(await db.order.findMany({where:{userId:req.user!.id},orderBy:{createdAt:"desc"},include:{items:{include:{product:true}}}})));
app.get("/api/admin/stats",auth,admin,async(_,res)=>{const[users,orders,products]=await Promise.all([db.user.count(),db.order.count(),db.product.count()]);res.json({users,orders,products});});
app.get("/api/admin/orders",auth,admin,async(_,res)=>res.json(await db.order.findMany({orderBy:{createdAt:"desc"},include:{user:true,items:{include:{product:true}}}})));
app.patch("/api/admin/orders/:id",auth,admin,async(req,res)=>res.json(await db.order.update({where:{id:req.params.id},data:{status:req.body.status}})));
app.post("/api/admin/categories",auth,admin,async(req,res)=>res.status(201).json(await db.category.create({data:{name:req.body.name,imageUrl:req.body.imageUrl}})));
app.post("/api/admin/products",auth,admin,async(req,res)=>{const{name,description,price,imageUrl,categoryId}=req.body;res.status(201).json(await db.product.create({data:{name,description,price,imageUrl,categoryId}}));});
app.patch("/api/admin/ads/:id",auth,admin,async(req,res)=>res.json(await db.adConfig.update({where:{id:req.params.id},data:req.body})));
app.use((_,res)=>res.status(404).json({message:"المسار غير موجود"}));
app.listen(Number(process.env.PORT)||4000,()=>console.log("API running"));
